import type { PanoramaTour } from "./types";

export const DEMO_PENTHOUSE_TOKEN = "demo-penthouse";

export const DEMO_PENTHOUSE_TOUR: PanoramaTour = {
  id: "tour_demo_penthouse_horizon",
  workspaceId: null,
  projectId: null,
  userId: "system_demo",
  title: "Penthouse Horizon Sky Villa (Demo 3 Phòng)",
  description:
    "Tour mẫu thực tế ảo căn Penthouse thông tầng cao cấp. Bao gồm Phòng Khách Skyview, Phòng Bếp & Quầy Bar Đảo, Phòng Ngủ Master Kính Cong với đầy đủ điểm neo chuyển phòng và chú thích vật liệu kiến trúc.",
  firstSceneId: "scene_demo_living_room",
  isPublic: true,
  shareToken: DEMO_PENTHOUSE_TOKEN,
  createdAt: 1773800000000,
  updatedAt: 1773800000000,
  scenes: [
    {
      id: "scene_demo_living_room",
      tourId: "tour_demo_penthouse_horizon",
      name: "Phòng Khách Skyview Horizon",
      assetId: "/landing/showcase-modern-living-room.webp",
      initialYaw: 15,
      initialPitch: -5,
      initialHfov: 105,
      orderIndex: 0,
      createdAt: 1773800000000,
      hotspots: [
        {
          id: "hs_living_to_kitchen",
          sceneId: "scene_demo_living_room",
          targetSceneId: "scene_demo_kitchen",
          type: "scene",
          pitch: -8,
          yaw: 55,
          title: "Sang Khu Bếp & Bar",
          description: "Di chuyển vào không gian bếp ẩm thực và quầy bar đảo sang trọng",
          createdAt: 1773800000000,
        },
        {
          id: "hs_living_to_master",
          sceneId: "scene_demo_living_room",
          targetSceneId: "scene_demo_master_bed",
          type: "scene",
          pitch: -6,
          yaw: -75,
          title: "Vào Phòng Ngủ Master",
          description: "Không gian nghỉ ngơi riêng tư hướng tầm nhìn hoàng hôn",
          createdAt: 1773800000000,
        },
        {
          id: "hs_living_info_sofa",
          sceneId: "scene_demo_living_room",
          targetSceneId: null,
          type: "info",
          pitch: -22,
          yaw: 10,
          title: "Sofa Minotti Roger Da Bò Ý",
          description: "Bộ ghế sofa module thủ công cao cấp, bọc da Nappa nguyên tấm màu cát sa mạc kết hợp bàn trà đá Marble Marquina.",
          createdAt: 1773800000000,
        },
        {
          id: "hs_living_info_glass",
          sceneId: "scene_demo_living_room",
          targetSceneId: null,
          type: "info",
          pitch: 8,
          yaw: 140,
          title: "Hệ Kính Hộp Low-E Cản Nhiệt",
          description: "Vách kính thông tầng 6.5m khung nhôm Schüco tiêu chuẩn Đức, cách âm 45dB và ngăn 99% tia UV.",
          createdAt: 1773800000000,
        },
      ],
    },
    {
      id: "scene_demo_kitchen",
      tourId: "tour_demo_penthouse_horizon",
      name: "Bếp & Quầy Bar Đảo Độc Lập",
      assetId: "/landing/showcase-luxury-kitchen.webp",
      initialYaw: -10,
      initialPitch: -8,
      initialHfov: 100,
      orderIndex: 1,
      createdAt: 1773800000000,
      hotspots: [
        {
          id: "hs_kitchen_to_living",
          sceneId: "scene_demo_kitchen",
          targetSceneId: "scene_demo_living_room",
          type: "scene",
          pitch: -7,
          yaw: -130,
          title: "Trở lại Phòng Khách",
          description: "Quay về không gian sinh hoạt chung và sảnh đón tiếp",
          createdAt: 1773800000000,
        },
        {
          id: "hs_kitchen_info_marble",
          sceneId: "scene_demo_kitchen",
          targetSceneId: null,
          type: "info",
          pitch: -18,
          yaw: -15,
          title: "Đảo Bếp Đá Marble Calacatta Gold",
          description: "Đá cẩm thạch tự nhiên nhập khẩu từ vùng Carrara Ý với đường vân vàng hổ phách tinh tế, chống thấm bề mặt công nghệ nano.",
          createdAt: 1773800000000,
        },
        {
          id: "hs_kitchen_info_appliances",
          sceneId: "scene_demo_kitchen",
          targetSceneId: null,
          type: "info",
          pitch: 2,
          yaw: 45,
          title: "Hệ Thiết Bị Âm Tủ Gaggenau 400 Series",
          description: "Lò nướng nhiệt phân, tủ bảo quản rượu vang 2 vùng nhiệt độ và bếp từ đa điểm không giới hạn vùng nấu.",
          createdAt: 1773800000000,
        },
      ],
    },
    {
      id: "scene_demo_master_bed",
      tourId: "tour_demo_penthouse_horizon",
      name: "Phòng Ngủ Master Panorama",
      assetId: "/landing/showcase-scandinavian-bedroom.webp",
      initialYaw: 20,
      initialPitch: -6,
      initialHfov: 105,
      orderIndex: 2,
      createdAt: 1773800000000,
      hotspots: [
        {
          id: "hs_master_to_living",
          sceneId: "scene_demo_master_bed",
          targetSceneId: "scene_demo_living_room",
          type: "scene",
          pitch: -6,
          yaw: 160,
          title: "Trở ra Sảnh & Phòng Khách",
          description: "Di chuyển ra khu vực phòng khách trung tâm",
          createdAt: 1773800000000,
        },
        {
          id: "hs_master_info_bed",
          sceneId: "scene_demo_master_bed",
          targetSceneId: null,
          type: "info",
          pitch: -20,
          yaw: 25,
          title: "Giường Ngủ Poliform Park 1",
          description: "Khung gỗ sồi tự nhiên bọc vải dệt Bỉ cao cấp, đệm cao su thiên nhiên phân vùng trọng lượng công thái học.",
          createdAt: 1773800000000,
        },
        {
          id: "hs_master_info_floor",
          sceneId: "scene_demo_master_bed",
          targetSceneId: null,
          type: "info",
          pitch: -35,
          yaw: -40,
          title: "Sàn Gỗ Xương Cá Walnut Mỹ",
          description: "Sàn gỗ óc chó Bắc Mỹ tự nhiên ghép kiểu Chevron nghệ thuật, phủ bóng dầu sáp Osmo thân thiện với môi trường.",
          createdAt: 1773800000000,
        },
      ],
    },
  ],
};

export function getDemoPenthouseTour(): PanoramaTour {
  // Return deep clone to prevent mutation
  return JSON.parse(JSON.stringify(DEMO_PENTHOUSE_TOUR)) as PanoramaTour;
}
