// Intake upload service (ADR 0003 / Ticket 06).
// Upload pipeline: intent → pending-upload + presigned PUT → finalize → quarantined → validate → ready|rejected
// Quota enforcer: 3 active intake, 20 intents/hour, 1GiB ready private.
// The queue consumer (`validateAsset`) is the validation worker entry point.

import type { Env } from "@/lib/bindings";
import type { AssetLifecycle } from "@/lib/fixtures/images";
import { INTAKE_EXPIRY_MS } from "@/lib/intake/expiry";
import { MAX_UPLOAD_BYTES, VALID_UPLOAD_MIMES } from "@/lib/fixtures/images";

// --- Types ---

export interface UploadIntentInput {
  userId: string;
  name: string;
  mimeType: string;
  size: number;
}

export interface UploadIntent {
  assetId: string;
  name: string;
  mimeType: string;
  size: number;
  key: string;
  expiresInSec: number;
  createdAt: number;
  presignedUrl?: string; // populated by the endpoint; not available in tests
}

export interface AssetRow {
  id: string;
  name: string;
  mime_type: string;
  size: number;
  lifecycle: AssetLifecycle;
  storage_key: string;
  user_id: string | null;
  declared_size: number | null;
  actual_size: number | null;
  width: number | null;
  height: number | null;
  created_at: number;
  updated_at: number;
  deleted_at: number | null;
  purge_at: number | null;
  recovery_until: number | null;
}

// Queue message payload for the ASSET_VALIDATE queue.
// Must be small (< 128KB per Queues limit).
export interface AssetValidationJob {
  assetId: string;
  key: string;
  declaredSize: number;
  declaredMime: string;
  attempt: number;
}

// --- Quota helpers ---

const MAX_ACTIVE_INTAKE = 3; // pending-upload + quarantined
const MAX_INTENTS_PER_HOUR = 20;
const MAX_READY_BYTES = 1 * 1024 * 1024 * 1024; // 1 GiB

type QuotaCheck = { ok: true } | { ok: false; reason: string };

export async function checkQuota(env: Env, userId: string): Promise<QuotaCheck> {
  // Admins are exempt from client intake throttling
  try {
    const user = await env.DB.prepare(
      `SELECT role FROM user WHERE id = ?1`
    ).bind(userId).first<{ role: string }>();
    if (user?.role === "admin") {
      return { ok: true };
    }
  } catch {
    // If user table query fails (e.g. in minimal mock contexts), continue standard checks
  }

  // Active intake count (pending-upload + quarantined)
  const active = await env.DB.prepare(
    `SELECT COUNT(*) AS cnt FROM assets WHERE user_id = ?1 AND lifecycle IN ('pending-upload', 'quarantined')`
  ).bind(userId).first<{ cnt: number }>();
  if (active && Number(active.cnt) >= MAX_ACTIVE_INTAKE) {
    return { ok: false, reason: `active intake limit (${MAX_ACTIVE_INTAKE}) reached` };
  }

  // Hourly intent rate
  const hourly = await env.DB.prepare(
    `SELECT COUNT(*) AS cnt FROM assets WHERE user_id = ?1 AND created_at > ?2`
  ).bind(userId, Date.now() - 3600_000).first<{ cnt: number }>();
  if (hourly && Number(hourly.cnt) >= MAX_INTENTS_PER_HOUR) {
    return { ok: false, reason: `hourly intent limit (${MAX_INTENTS_PER_HOUR}) reached` };
  }

  // Total ready private bytes
  const readyBytes = await env.DB.prepare(
    `SELECT COALESCE(SUM(actual_size), 0) AS total FROM assets WHERE user_id = ?1 AND lifecycle = 'ready'`
  ).bind(userId).first<{ total: number }>();
  if (readyBytes && Number(readyBytes.total) >= MAX_READY_BYTES) {
    return { ok: false, reason: `ready private storage limit (1GiB) reached` };
  }

  return { ok: true };
}

// --- Intake pipeline ---

/**
 * Creates an upload intent: validates input, checks quotas, creates the D1 row,
 * and returns the intent + minimal info for the endpoint to generate a presigned URL.
 *
 * Quota check: 3 active intake, 20 intents/hour, 1GiB ready private.
 * The presigned URL is generated by the caller (needs S3 API credentials).
 */
export async function createUploadIntent(
  env: Env,
  input: UploadIntentInput
): Promise<UploadIntent> {
  // Input validation
  if (!VALID_UPLOAD_MIMES.includes(input.mimeType as (typeof VALID_UPLOAD_MIMES)[number])) {
    throw new Error(`unsupported mime type: ${input.mimeType}`);
  }
  if (input.size > MAX_UPLOAD_BYTES) {
    throw new Error(`size exceeds ${MAX_UPLOAD_BYTES} bytes`);
  }

  // Quota check
  const quota = await checkQuota(env, input.userId);
  if (!quota.ok) {
    throw new Error(`quota exceeded: ${quota.reason}`);
  }

  const assetId = crypto.randomUUID();
  const key = `quarantine/${assetId}`;
  const now = Date.now();
  const purgeAt = now + INTAKE_EXPIRY_MS;

  await env.DB.prepare(
    `INSERT INTO assets (id, name, mime_type, size, lifecycle, storage_key, user_id, declared_size, created_at, updated_at, purge_at)
     VALUES (?1, ?2, ?3, ?4, 'pending-upload', ?5, ?6, ?7, ?8, ?8, ?9)`
  )
    .bind(assetId, input.name, input.mimeType, input.size, key, input.userId, input.size, now, purgeAt)
    .run();

  return {
    assetId,
    name: input.name,
    mimeType: input.mimeType,
    size: input.size,
    key,
    expiresInSec: 10 * 60,
    createdAt: now,
  };
}

/**
 * Finalize the upload: verify the object exists in R2, atomically transition
 * the Asset from pending-upload → quarantined, and send a validation job to
 * the ASSET_VALIDATE queue. Converges to a single job: if the Asset is already
 * quarantined, this is a no-op (idempotent replay).
 */
export async function finalizeUpload(
  env: Env,
  assetId: string
): Promise<{ ok: true; lifecycle: AssetLifecycle } | { ok: false; reason: string }> {
  // Read current asset state
  const asset = await env.DB.prepare(
    `SELECT id, lifecycle, storage_key, user_id, declared_size, mime_type FROM assets WHERE id = ?1`
  ).bind(assetId).first<AssetRow>();

  if (!asset) {
    return { ok: false, reason: "asset not found" };
  }

  // Already quarantined or beyond → no-op (idempotent convergence)
  if (asset.lifecycle !== "pending-upload") {
    return { ok: true, lifecycle: asset.lifecycle };
  }

  // Verify the object exists in R2 at the quarantine key
  if (!asset.storage_key) {
    return { ok: false, reason: "no storage key" };
  }
  const obj = await env.HD_PRIVATE.head(asset.storage_key);
  if (!obj) {
    return { ok: false, reason: "object not uploaded yet" };
  }

  // Atomic transition: pending-upload → quarantined
  const now = Date.now();
  const result = await env.DB.prepare(
    `UPDATE assets SET lifecycle = 'quarantined', actual_size = ?2, updated_at = ?3, purge_at = ?4
     WHERE id = ?1 AND lifecycle = 'pending-upload'`
  )
    .bind(assetId, obj.size, now, now + INTAKE_EXPIRY_MS)
    .run();

  if (result.meta.changes === 0) {
    // Race: another finalize already transitioned it
    return { ok: true, lifecycle: "quarantined" };
  }

  // Send validation job to queue (idempotent: the queue handler checks lifecycle)
  const job: AssetValidationJob = {
    assetId,
    key: asset.storage_key,
    declaredSize: asset.declared_size ?? obj.size,
    declaredMime: asset.mime_type,
    attempt: 1,
  };
  await env.ASSET_VALIDATE.send(job);

  return { ok: true, lifecycle: "quarantined" };
}

/**
 * Delete an Asset: immediately hide, revoke access, start 30-day recovery timer.
 * Returns the asset ID on success, null if not found or already deleted.
 */
export async function deleteAsset(env: Env, assetId: string): Promise<string | null> {
  const now = Date.now();
  const recoveryPeriod = 30 * 24 * 3600_000; // 30 days

  const result = await env.DB.prepare(
    `UPDATE assets SET lifecycle = 'deleted', deleted_at = ?2, recovery_until = ?3, updated_at = ?2
     WHERE id = ?1 AND lifecycle != 'deleted'`
  )
    .bind(assetId, now, now + recoveryPeriod)
    .run();

  if (result.meta.changes === 0) return null;
  return assetId;
}

/**
 * Get the lifecycle of an Asset. Returns null if not found.
 */
export async function getAssetLifecycle(env: Env, assetId: string): Promise<AssetLifecycle | null> {
  const row = await env.DB.prepare(
    `SELECT lifecycle FROM assets WHERE id = ?1`
  ).bind(assetId).first<{ lifecycle: AssetLifecycle }>();
  return row?.lifecycle ?? null;
}